apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: release-control
resources:
  - ../../kubernetes
  - service-account.yaml
  - rbac.yaml
configMapGenerator:
  - name: release-control-runtime
    files:
      - runtime-observers.json
patches:
  - path: deployment.yaml
